<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { chat, messages, sessions, type AgentAction, type Message, type Session } from '../api'; import MessageBubble from '../components/MessageBubble.vue'; import SessionList from '../components/SessionList.vue'; import StateView from '../components/StateView.vue'; import ActionConfirm from '../components/ActionConfirm.vue';
const list=ref<Session[]>([]), active=ref<string>(), history=ref<Message[]>([]), draft=ref(''), pending=ref(false), thinking=ref(localStorage.getItem('agent-thinking')==='true'), error=ref(''), lastMessage=ref(''), lastUserMessageId=ref('');
async function reload(){list.value=await sessions();} async function select(id:string){active.value=id;sessionStorage.setItem('agent-active-session',id);history.value=await messages(id);const last=history.value.at(-1);const retryUser=last?.status==='FAILED'?[...history.value].reverse().find(message=>message.role==='USER'):undefined;if(retryUser){lastMessage.value=retryUser.content;lastUserMessageId.value=retryUser.messageId;}} function create(){active.value=undefined;sessionStorage.removeItem('agent-active-session');history.value=[];error.value='';lastUserMessageId.value='';}
function changeThinking(){localStorage.setItem('agent-thinking',String(thinking.value));}
async function send(retryUserMessageId?:string){const retrying=typeof retryUserMessageId==='string'&&retryUserMessageId.length>0;if((!retrying&&!draft.value.trim())||pending.value)return;const text=retrying?lastMessage.value:draft.value.trim();if(!text)return;lastMessage.value=text;if(!retrying)draft.value='';pending.value=true;error.value='';const assistant:Message={messageId:'pending',role:'ASSISTANT',content:'',status:'STREAMING',createdAt:''};const user:Message|undefined=retrying?undefined:{messageId:crypto.randomUUID(),role:'USER',content:text,status:'COMPLETED',createdAt:''};if(user)history.value.push(user);history.value.push(assistant);try{await chat({sessionId:active.value,message:text,thinkingEnabled:thinking.value,retryUserMessageId:retrying?retryUserMessageId:undefined},({event,data})=>{if(event==='message_start'){active.value=String(data.sessionId);sessionStorage.setItem('agent-active-session',active.value);lastUserMessageId.value=String(data.userMessageId||'');if(user)user.messageId=lastUserMessageId.value;assistant.messageId=String(data.messageId||assistant.messageId);}if(event==='delta')assistant.content+=String(data.text||'');if(event==='action_required'){assistant.content=assistant.content||'请确认以下操作';assistant.action=data as unknown as AgentAction;}if(event==='error')error.value='模型服务暂不可用，请重试。';});assistant.status=error.value?'FAILED':'COMPLETED';await reload();}catch(e){error.value=e instanceof Error?e.message:'发送失败';assistant.status='FAILED';}finally{pending.value=false;}}
function retry(){if(!lastMessage.value||pending.value)return;if(lastUserMessageId.value)void send(lastUserMessageId.value);else{draft.value=lastMessage.value;void send();}}
onMounted(async()=>{await reload();const previous=sessionStorage.getItem('agent-active-session');if(previous&&list.value.some(item=>item.sessionId===previous)){try{await select(previous);}catch{sessionStorage.removeItem('agent-active-session');}}});
</script><template><div class="shell"><SessionList :items="list" :active="active" @select="select" @create="create"/><section class="chat"><header><h1>小猫账本 Agent</h1><label><input v-model="thinking" type="checkbox" @change="changeThinking"> 深度思考</label></header><div class="messages"><StateView v-if="!history.length" text="问问本月预算、账单或消费趋势吧。"/><template v-for="message in history" :key="message.messageId"><MessageBubble :role="message.role" :content="message.content || (pending ? '正在分析…' : '')" :failed="message.status==='FAILED'"/><ActionConfirm v-if="message.action" :action="message.action"/></template></div><p v-if="error" class="error">{{error}} <button v-if="lastMessage" class="retry" :disabled="pending" @click="retry">重试上一条</button></p><form @submit.prevent="send()"><textarea v-model="draft" maxlength="2000" placeholder="例如：这个月餐饮花了多少？"/><button :disabled="pending">{{pending?'发送中…':'发送'}}</button></form></section></div></template><style scoped>.shell{height:100vh;display:grid;grid-template-columns:260px 1fr}.chat{display:grid;grid-template-rows:auto 1fr auto;padding:24px;gap:12px}.chat header{display:flex;justify-content:space-between;align-items:center}.messages{overflow:auto;max-width:900px;width:100%;justify-self:center}.error{color:#b91c1c}.retry{padding:6px 10px;margin-left:8px}form{display:flex;gap:12px;max-width:900px;width:100%;justify-self:center}textarea{flex:1;min-height:48px;padding:12px;border:1px solid var(--border);border-radius:8px}button{border:0;border-radius:8px;padding:0 20px;background:var(--primary);color:#fff}@media(max-width:700px){.shell{grid-template-columns:1fr}.shell aside{display:none}}</style>
