<script setup lang="ts">
import { computed, ref } from 'vue'; import { cancelAction, confirmAction, type AgentAction } from '../api';
/** 展示 Agent 写操作的内容与状态，并要求用户显式确认或取消。 */
const props=defineProps<{action:AgentAction}>(); const current=ref(props.action); const busy=ref(false); const error=ref('');
const fieldLabels:Record<string,string>={expenseId:'开支编号',categoryId:'科目编号',amount:'金额（元）',expenseDate:'日期',note:'备注',yearMonth:'月份',items:'预算明细',name:'科目名称',sortOrder:'排序'};
const statusLabels:Record<AgentAction['status'],string>={PENDING_CONFIRMATION:'待确认',EXECUTING:'执行中',CANCELLED:'已取消',EXPIRED:'已过期',STALE:'账本已变化，请重新发起',EXECUTED:'已执行',FAILED:'执行失败'};
const rows=computed(()=>Object.entries(current.value.payload).map(([key,value])=>({key,label:fieldLabels[key]||key,value:formatValue(value)})));
const resultMessage=computed(()=>typeof current.value.result?.message==='string'?current.value.result.message:'');
function formatValue(value:unknown):string { if(Array.isArray(value)) return value.map((item,index)=>`${index+1}. ${formatValue(item)}`).join('\n'); if(value&&typeof value==='object') return Object.entries(value as Record<string,unknown>).map(([key,item])=>`${fieldLabels[key]||key}：${formatValue(item)}`).join('，'); return value==null||value===''?'无':String(value); }
async function run(kind:'confirm'|'cancel'){busy.value=true;error.value='';try{current.value=kind==='confirm'?await confirmAction(current.value.actionId):await cancelAction(current.value.actionId);}catch(e){error.value=e instanceof Error?e.message:'操作失败';}finally{busy.value=false;}}
</script><template><section class="card"><strong>{{current.summary}}</strong><dl><template v-for="row in rows" :key="row.key"><dt>{{row.label}}</dt><dd>{{row.value}}</dd></template></dl><p>状态：{{statusLabels[current.status]}}</p><p v-if="resultMessage" class="result">{{resultMessage}}</p><div v-if="current.status==='PENDING_CONFIRMATION'"><button :disabled="busy" @click="run('confirm')">确认执行</button><button class="secondary" :disabled="busy" @click="run('cancel')">取消</button></div><small v-if="error">{{error}}</small></section></template><style scoped>.card{margin:8px 0;padding:16px;border:1px solid #f59e0b;border-radius:12px;background:#fffbeb}.card dl{display:grid;grid-template-columns:auto 1fr;gap:6px 12px}.card dt{color:var(--muted)}.card dd{margin:0;overflow-wrap:anywhere;white-space:pre-line}.card button{border:0;border-radius:8px;padding:8px 14px;background:var(--primary);color:#fff;margin-right:8px}.card .secondary{background:#64748b}.card small{color:#b91c1c}.result{color:#b91c1c}</style>
